### ISSUE TITLE
check bitcoin address before usage

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/BitcoinVault#5]
check the bitcoin address in the app and if possible already in the browser.

Maybe this could help: https://github.com/bitcoinjs/bs58check

**Comment by MBeuttler** [comment]
https://github.com/IUNO-TDM/JuiceMarketplaceWebsite/commit/ad02ff912b90ab226260bddd164a9410cf13ff26

**Comment by bockha** [comment]
[bs58check](https://www.npmjs.com/package/bs58check)

```npm install bs58check```

```
var bs58check = require('bs58check')
 
var decoded = bs58check.decode('5Kd3NBUAdUnhyzenEwVLy9pBKxSwXvE9FMPyR4UKZvpe6E3AgLr')
 
console.log(decoded)
// => <Buffer 80 ed db dc 11 68 f1 da ea db d3 e4 4c 1e 3f 8f 5a 28 4c 20 29 f7 8a d2 6a f9 85 83 a4 99 de 5b 19>
 
console.log(bs58check.encode(decoded))
// => 5Kd3NBUAdUnhyzenEwVLy9pBKxSwXvE9FMPyR4UKZvpe6E3AgLr
```
